name: Build Android APKs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Gradle 7.5.1
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1

      - name: Build Admin App
        run: |
          cd AdminApp
          gradle assembleDebug --no-daemon

      - name: Build User App
        run: |
          cd UserApp
          gradle assembleDebug --no-daemon

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: Built-APKs
          path: |
            AdminApp/app/build/outputs/apk/debug/app-debug.apk
            UserApp/app/build/outputs/apk/debug/app-debug.apk
